- name: show return value of command module
  hosts: testserver
  tasks:
    - name: capture output of id command
      command: id -un
      register: login
    - debug: var=login
  hosts: testserver
  tasks:
    - name: capture output of id command
      command: ls -al
      register: ls-al
    - debug: var=ls-al