- name: play to setup web server
  hosts: testserver
  tasks:
    - name: install apache
      yum:
        name: httpd
        state: latest
    - name: copy index.html 
      copy:
        src: file/index.html
        dest: /var/www/html/index.html
    - name: start apache service
      service:
        name: httpd
        state: started
        enabled: True