- name: config webserver with nginx
  hosts: testserver
  tasks:
    - name: install nginx
      yum: name=nginx update_cache=yes
    - name: copy configfile
      copy: src=/etc/nginx/nginx.conf dest=/etc/nginx/nginx.conf
    - name: copy index.html
      template: src=/var/www/html/index.html dest=/usr/share/nginx/html/index.html mode=0644
    - name: restart nginx
      service: name=nginx state=restarted