- name: set the nginx config file
  template: src=nginx.conf.j2 dest=/etc/nginx/conf.d/mezzanine.conf
  notify: restart nginx
  become: True
- name: create ssl serificates
  command: >
    openssl req -new -x509 -nodes -out {{ mezzanine_proj_name }}.crt -keyout {{ mezzanine_proj_name }}.key -subj '/CN={{ domains[0] }}' -days 3650 
    chdir={{ mezzanine_conf_path }} 
    creates={{ mezzanine_conf_path }}/{{mezzanine_proj_name}}.crt
  become: True
  when: ssl_enabled
  notify: restart nginx
